# fly.toml app configuration file generated for fly-log-shipper-mcont on 2023-05-28T20:47:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-log-shipper-mcont"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[metrics]
  port = 9598
  path = "/metrics"
